---@class lspconfig.Opts
---@field capabilities? table<string,lsp.ClientCapabilities>
---@field on_attach? table<string,fun(client: vim.lsp.Client, bufnr: integer)>
---@field settings? table<string, table>
