---@class lspconfig.Opts
---@field diagnostic? vim.diagnostic.Opts
---@field settings? table<string, table>
---@field capabilities? lsp.ClientCapabilities
---@field on_attach? fun(client: vim.lsp.Client, bufnr: integer)
