return {
    "nvim-treesitter/nvim-treesitter",
    build = ":TSUpdate",
    event = { "BufReadPost", "BufNewFile", "BufWritePre", "VeryLazy" },
    cmd = { "TSUpdate", "TSInstall", "TSLog", "TSUninstall" },
    main = "utils.plugins.treesitter",
    ---@module "utils.plugins.treesitter"
    ---@type utils.treesitter.opts
    opts = {
        ensure_installed = {
            "c",
            "lua",
            "bash",
            "zsh",
            "vim",
            "vimdoc",
            "query",
            "regex",
            "markdown",
            "markdown_inline",
            "html",
            "javascript",
            "latex",
            "norg",
            "scss",
            "svelte",
            "tsx",
            "typst",
            "vue",
        },
        highlight = { enabled = true },
        fold = { enabled = true },
        indent = { enabled = true },
    },
}
